### ISSUE TITLE
uninitialized constant Sidekiq::Rescue::Middleware

### ISSUE THREAD

**Issue by neudabei** [moofkit/sidekiq-rescue#2]
Hi moofit,

Thanks so much for building this. It was just what I was looking for.

I couldn't get Sidekiq to start because of the initializer

```ruby
uninitialized constant Sidekiq::Rescue::Middleware

    chain.add Sidekiq::Rescue::Middleware
                             ^^^^^^^^^^^
```

It seems to work when I add the Dsl, rather than the middleware, i.e.

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Rescue::Dsl
  end
end
```

Is that the right solution or am I holding it wrong?

**Comment by moofkit** [comment]
Hey @neudabei!
Thank you for raising this issue!
Yeah, there is a mistake in the README...

The right way to activate the middleware:
```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Rescue::ServerMiddleware
  end
end
```

You were speaking about `Sidekiq::Rescue::Dsl`. This module you can include in your sidekiq job to use sidekiq_rescue dsl
```ruby
class MyJob
  include Sidekiq::Job
  include Sidekiq::Rescue::Dsl

  sidekiq_rescue ExpectedError

  def perform(*)
    # ...
  end
end
```
I hope it would be helpful!

I will fix the README, thanks!
